apiVersion: v2
type: application
appVersion: v0.8.3
description: A Matrix-WhatsApp puppeting bridge https://maunium.net/go/mautrix-whatsapp
name: mautrix-whatsapp
version: 1.3.0
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - whatsapp
home: https://maunium.net/go/mautrix-whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update dock.mau.dev/mautrix/whatsapp docker tag to v0.8.6 ([654929e](https://github.com/halkeye-helm-charts/mautrix-whatsapp/commit/654929eb36e3c02a0e9a5be2f1abf7593757b246))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: whatsapp
      image: "dock.mau.dev/mautrix/whatsapp:v0.9.0"
