apiVersion: v2
type: application
appVersion: v0.8.3
description: A Matrix-WhatsApp puppeting bridge https://maunium.net/go/mautrix-whatsapp
name: mautrix-whatsapp
version: 1.4.0
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - whatsapp
home: https://maunium.net/go/mautrix-whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update dock.mau.dev/mautrix/whatsapp docker tag to v0.9.0 ([45abe23](https://github.com/halkeye-helm-charts/mautrix-whatsapp/commit/45abe237ea6793e585df579d96dbaa61861dcc88))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: whatsapp
      image: "dock.mau.dev/mautrix/whatsapp:v0.9.0"
