apiVersion: v2
type: application
appVersion: v0.8.3
description: A Matrix-WhatsApp puppeting bridge https://maunium.net/go/mautrix-whatsapp
name: mautrix-whatsapp
version: 1.2.0
keywords:
  - synapse
  - chat
  - matrix
  - bridge
  - whatsapp
home: https://maunium.net/go/mautrix-whatsapp
sources:
  - https://github.com/mautrix/whatsapp
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |2
     - "**deps:** update dock.mau.dev/mautrix/whatsapp docker tag to v0.8.4 ([886942f](https://github.com/halkeye-helm-charts/mautrix-whatsapp/commit/886942ffefd3a944cd831a9cb28603d834b32b6f))"
  artifacthub.io/containsSecurityUpdates: 'false'
  artifacthub.io/images: |
    - name: whatsapp
      image: "dock.mau.dev/mautrix/whatsapp:v0.8.4"
